shiny:
  ingress:
    enabled: true
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: monshiny.lab.sspcloud.fr
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
      - hosts:
        - monshiny.lab.sspcloud.fr